// <auto-generated />
using System;
using HypeHealthAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HypeHealthAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HypeHealthAPI.Models.DailyMoodLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_DailyMoodLog_UserId");

                    b.HasIndex("UserId", "LogDate")
                        .IsUnique();

                    b.ToTable("DailyMoodLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogDate = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Score = 8,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            LogDate = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Score = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            LogDate = new DateTime(2026, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Score = 9,
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            LogDate = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Score = 7,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            LogDate = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Score = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            LogDate = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Score = 8,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("HypeHealthAPI.Models.KudosCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("IX_KudosCard_ReceiverId");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("IX_KudosCard_SenderId");

                    b.ToTable("KudosCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Message = "@David saved my deployment pipeline at midnight! Incredible work.",
                            ReceiverId = 3,
                            SenderId = 1,
                            Timestamp = new DateTime(2026, 5, 23, 6, 47, 12, 397, DateTimeKind.Utc).AddTicks(768)
                        },
                        new
                        {
                            Id = 2,
                            Message = "@Sarah handled the enterprise API configuration perfectly. Thanks for unblocking!",
                            ReceiverId = 4,
                            SenderId = 3,
                            Timestamp = new DateTime(2026, 5, 23, 9, 47, 12, 397, DateTimeKind.Utc).AddTicks(773)
                        },
                        new
                        {
                            Id = 3,
                            Message = "Shoutout to @Sanjana for completing the complex DB scheme mapping ahead of schedule!",
                            ReceiverId = 1,
                            SenderId = 4,
                            Timestamp = new DateTime(2026, 5, 23, 11, 17, 12, 397, DateTimeKind.Utc).AddTicks(777)
                        });
                });

            modelBuilder.Entity("HypeHealthAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SprintVelocity")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "emp@company.com",
                            PasswordHash = "$2a$11$mSeJEUK/usSIy52Lb7NjHu2M91Ll3327m16OM8hQcLG5IuCw.9B5K",
                            Role = "Employee",
                            SprintVelocity = 42.50m,
                            Username = "Sanjana Patil"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mgr@company.com",
                            PasswordHash = "$2a$11$mSeJEUK/usSIy52Lb7NjHu2M91Ll3327m16OM8hQcLG5IuCw.9B5K",
                            Role = "Manager",
                            SprintVelocity = 0.00m,
                            Username = "Alex Mercer"
                        },
                        new
                        {
                            Id = 3,
                            Email = "david@company.com",
                            PasswordHash = "$2a$11$mSeJEUK/usSIy52Lb7NjHu2M91Ll3327m16OM8hQcLG5IuCw.9B5K",
                            Role = "Employee",
                            SprintVelocity = 38.20m,
                            Username = "David Miller"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sarah@company.com",
                            PasswordHash = "$2a$11$mSeJEUK/usSIy52Lb7NjHu2M91Ll3327m16OM8hQcLG5IuCw.9B5K",
                            Role = "Employee",
                            SprintVelocity = 45.10m,
                            Username = "Sarah Jenkins"
                        });
                });

            modelBuilder.Entity("HypeHealthAPI.Models.DailyMoodLog", b =>
                {
                    b.HasOne("HypeHealthAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HypeHealthAPI.Models.KudosCard", b =>
                {
                    b.HasOne("HypeHealthAPI.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HypeHealthAPI.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });
#pragma warning restore 612, 618
        }
    }
}
